### ISSUE TITLE
Initial Seed & Color by Id

### ISSUE THREAD

**Issue by jeffg2k** [sterlingwes/RandomColor#3]
Two things that were missing for me in this script.  This states it's useful for charts and diagrams, but while you may want random distinct colors, you often want them to be the same random colors each time the page is loaded.  So it would be nice to have an initial seed value, instead of a Random value based on system time.  Perhaps something like this:

```
var RColor = function(seed) {
    this.hue            = seed || Math.random(),
    this.goldenRatio    = 0.618033988749895;
    this.hexwidth       = 2;
};
```

Secondly, I often have Id's set to particular sets of data.  Group 1 gets one color, Group 2 another, etc.  So it would be nice to allow it to get that same random color given an Id.  Perhaps something like this, after setting this up in the initialization.

this.initialhue = this.hue;

```
RColor.prototype.getById = function(id,hex,saturation,value) {
    if (id % 1 !== 0) return this.get(hex,saturation,value);
    hueval = this.initialhue;
    hueval += this.goldenRatio * id;
    hueval %= 1;
    if(typeof saturation !== "number")  saturation = 0.5;
    if(typeof value !== "number")       value = 0.95;
    var rgb = this.hsvToRgb(this.hue,saturation,value);
    if(hex)
        return "#" +  this.padHex(rgb[0].toString(16))
                    + this.padHex(rgb[1].toString(16))
                    + this.padHex(rgb[2].toString(16));
    else
        return rgb;
};
```

**Comment by sterlingwes** [comment]
I know it's been a while but wanted to update this since I've recently reworked this library.

I thought about this some more and I think it should be the job of whatever code is leveraging `rcolor` to take care of saving or associating colors with IDs. The new API should make it easier for folks to override the hue, saturation and value options.

Going to focus on making sure this does one thing and one thing well (generating random colors). Appreciate you sharing your use case though!
